INSERT INTO [dbo].[Products] ([Id], [Name], [UnitPrice], [StockAmoun]) VALUES (1, N'Fare', CAST(21 AS Decimal(18, 0)), 12)
INSERT INTO [dbo].[Products] ([Id], [Name], [UnitPrice], [StockAmoun]) VALUES (2, N'Mobil', CAST(21 AS Decimal(18, 0)), 12)
INSERT INTO [dbo].[Products] ([Id], [Name], [UnitPrice], [StockAmoun]) VALUES (3, N'knl', CAST(76 AS Decimal(18, 0)), 90)
INSERT INTO [dbo].[Products] ([Id], [Name], [UnitPrice], [StockAmoun]) VALUES (4, N'isa', CAST(0 AS Decimal(18, 0)), 1)
INSERT INTO [dbo].[Products] ([Id], [Name], [UnitPrice], [StockAmoun]) VALUES (5, N'jgk', CAST(85 AS Decimal(18, 0)), 85687)
INSERT INTO [dbo].[Products] ([Id], [Name], [UnitPrice], [StockAmoun]) VALUES (6, N'jhk', CAST(78687 AS Decimal(18, 0)), 586)
INSERT INTO [dbo].[Products] ([Id], [Name], [UnitPrice], [StockAmoun]) VALUES (1007, N'aynur', CAST(5675 AS Decimal(18, 0)), 453)
